
name: "Get Change Types of PR"
description: "Create comment on pull request, if exists does nothing."
author: "mcmcgrath13"
inputs:
  GITHUB_TOKEN:
    description: "set secrets.GITHUB_TOKEN here"

runs:
  using: "node12"
  main: "dist/index.js"
